### ISSUE TITLE
Partition() doesn't play nicely with data.table

### ISSUE THREAD

**Issue by GittinOld** [hadley/multidplyr#13]
Fails with incorrect error message when data.table is used as input to partition.

my data.table is too large to replicate here, but perhaps it is enough to try:

    cl <- create_cluster(3)
    set_default_cluster(cl)

    iris %>% partition(Species) #works
    
    library(data.table)
    data.table(iris) %>% partition(Species) #fails "Error: length(values) == length(cluster) is not TRUE"

**Comment by hadley** [comment]
There's currently no support for data.table.

**Comment by phineas-pta** [comment]
now is it possible now with `dtplyr` ? i tried but it's 2x slower when combining `dtplyr` and `multidplyr`
