### ISSUE TITLE
Resolving Dependencies on Nodes

### ISSUE THREAD

**Issue by cwbishop** [hadley/multidplyr#14]
Hello,

More of a general question than an issue - my apologies if this is the wrong forum for such an inquiry. I'd be grateful if you could point me to the correct forum if this is the case.

Perhaps I'm missing something obvious, but I'm not sure how best to leverage partition() in combination with do() with custom functions with dependencies. As a simple example, see below ...

library(dplyr)
library(multidplyr)
library(nycflights13)

cluster <- create_cluster(8)
set_default_cluster(cluster)

myfun <- function(x) { mean(x, na.rm=TRUE) }

system.time({
    flights %>% 
        partition() %>%
        summarise(myfun(dep_delay)) %>% 
        collect()
})

This fails unless I manually assign the function value on each node using the following preamble:

cluster %>% cluster_assign_value('myfun', myfun)

This is easy enough to do with a single function, but I am trying to apply functions with sometimes rather involved dependencies on other custom functions living in my environment. I also rely on ~20 - 30 libraries for much of my work and pushing each of these out to each node in the cluster is costly.

I can certainly write helper functions to push libraries and relevant local functions, but wanted to know if there's a more straightforward (or automatic) way of doing this? Or if I'm missing a key concept entirely?

-Chris

**Comment by hadley** [comment]
Yes, that's the challenge of parallel computing. You need to determine what should be available on each node, and make sure it's there. I don't think it's possible to do it automatically.

**Comment by cwbishop** [comment]
Thank you so much for your speedy response.

I do not know nearly enough to comment on this intelligently, but wanted to mention that some of the other parallel processing packages I use (e.g., foreach's %dopar% operator coupled with doParallel) seem to handle this situation. But I do not have the background to say why or if the backends are at all comparable to what mutlidplyr is doing.
