### ISSUE TITLE
"multiplyr" package do not handle integer64 columns correctly.

### ISSUE THREAD

**Issue by gigamori** [hadley/multidplyr#19]
Through multidplyr processing (partition() -> collect()), 
integer64 columns are converted to "numeric" automatically, however interger columns are not.

Example: 

```r
dt <- data.table(x=1:5, y=6:10)
dt$x <- as.integer64(dt$x)

class(dt$x)
# [1] "integer64"
class(dt$y)
# [1] "integer"

dt %>% partition %>% collect -> dt2

class(dt2$x)
# [1] "numeric" -> !!!
class(dt2$y)
# [1] "integer"
```

My environment is: 

```r
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
```

multidplyr package version is: 

‘0.0.0.9000’

**Comment by hadley** [comment]
Unfortunately mutlidplyr does not currently support data.table
