### ISSUE TITLE
Utility function for attaching functions?

### ISSUE THREAD

**Issue by Mullefa** [hadley/multidplyr#22]
(probably) dubious implementation, but something like:

``` R
cluster_assign_func <- function(cl, f) {
  fname <- as.character(substitute(f))
  stopifnot(is.function(f))
  cluster_assign_value(cl, fname, f)
}
```

**Comment by julou** [comment]
I find it indeed useful…
I also derived the following to attach any object:

```
cluster_assign_obj <- function(cl, x) {
  name <- as.character(substitute(x))
  stopifnot(exists(name))
  cluster_assign_value(cl, name, x)
}
```

**Comment by cboettig** [comment]
:+1: @Mullefa thanks for the implementation.  Given that parallelizing `do()` over a complex function call is probably one of the more promising use cases, a utility function like this would be great.

**Comment by hadley** [comment]
Implemented as `cluster_copy`
