### ISSUE TITLE
can not load multiple packages through `cluster_library`

### ISSUE THREAD

**Issue by eribul** [hadley/multidplyr#27]
According to `?cluster_library` (regarding its argument):

> `packages` A character vector of package names

But if I try to load multilpe packages, such as:
`cluster_library(c("dplyr", "icd"))`

I get the following error:

```
Error in library(packages, character.only = TRUE) : 
  'package' must be of length 1
```

And if I indeed take a look at the source code of `cluster_library` it seems like it is trynig to pass the `packages` (plural) from `cluster_library` to `package` (singular) in `library`

**Comment by Ax3man** [comment]
This is identical to issue #21, by the way.

**Comment by eribul** [comment]
Ups, you're right! Thanks!
