### ISSUE TITLE
group_by groups within partitions only

### ISSUE THREAD

**Issue by wosiu** [hadley/multidplyr#29]
Let's assume that we've got 7 cores as worknodes.

`data %>% partition() %>% group_by(transactionID) %>% collect()`

The thing is that after collect() here we've got still even 7 rows with the same transactionID representing the same one group (one for each core). 
Thus there is a need to call the same group_by one more time after collect() to get results we wanted intuitively (just to merge results from different cores).

Instead of that, multidplyr could overwrite dplyr's group_by in such simple way:

multidplyr:group_by(...):
   if (currently_working_in_partitions) {
      dplyr:group_by(...) %>% collect() %>% dplyr:group_by(...) %>% partitions()
   } else {
      dplyr:group_by(...)
   }
}

^ I'm not 100% sure if that would give always correct results for all agregate functions
Ofc it would be even better, if such operation is written by design in multicore way (e.g. some map-reduce paradigm on cores).

or safer as workaround (but not using power of multi-cores):

multidplyr:group_by(...):
   if (currently_working_in_partitions) {
      collect() %>% dplyr:group_by(...)   %>% partitions()
   } else {
      dplyr:group_by(...) %>%
   }
}

**Comment by hadley** [comment]
I think you're asking for `repartition()`, #34.
