### ISSUE TITLE
summarize_each doesn't seem to work

### ISSUE THREAD

**Issue by kendonB** [hadley/multidplyr#30]
Hi,

I get an error message when using summarize_each with multidplyr:

```
library(dplyr)
library(multidplyr)
library(nycflights13)
flights %>% 
  partition(cluster = create_cluster(2)) %>%
    summarise_each(funs(mean(., na.rm = TRUE)), matches("dep_delay")) %>% 
  collect()
Error in UseMethod("tbl_vars") : 
  no applicable method for 'tbl_vars' applied to an object of class "party_df"

```

Can't immediately see what's going wrong. Hope this helps!

**Comment by gregkoytiger** [comment]
I second this issue, having functioning summarize_all / summarize_each would be such a powerful use case for multidplyr. I frequently encounter situations where I have many groups and many features to summarize across those groups where writing feature1 = mean(feature1), etc. becomes impossible.

**Comment by KatarzynaKlamecka** [comment]
Hi,
I also have these problem and it would be nice to have possibility to use also mutate_each for multidplyr.
I'm looking forward for changes! :)
