### ISSUE TITLE
Overhead is excrutiating

### ISSUE THREAD

**Issue by kendonB** [hadley/multidplyr#32]
I have an application where the input data.frame size is around 60GB and the moving-memory-around stage is taking almost as long as the computation I want to run - possibly will be longer with the collect stage.

I know this isn't a particularly helpful issue, but it would extremely helpful if someone could work out a way to not have to do the moving-memory-around stage, perhaps with something inspired by Rcppparallel, which I can easily use for computations which are ungrouped.

multidplyr seems like it can only be helpful in situations where the computation stage is intensive, which, for most big data applications, isn't the case.

**Comment by rfaelens** [comment]
I suggest you load your input data.frame directly into the cluster nodes. See https://github.com/hadley/multidplyr/blob/master/vignettes/multidplyr.md#limitations
