### ISSUE TITLE
List columns get copied when partitioning

### ISSUE THREAD

**Issue by kendonB** [hadley/multidplyr#37]
The example:

```
tmp <- data_frame(i = rep(1:4, 100000)) %>% 
  group_by(i) %>% 
  nest() %>% 
  mutate(iris = rep(list(iris), 4)) %>% 
  unnest(data, .drop = FALSE) 
pryr::mem_used() # 42.6 MB
# This doesn't use much memory on the main process as the repeated lists are just pointers

cl <- create_cluster(4)
tmp2 <- tmp  %>% 
  # This uses heaps of memory as iris is copied 100000 times
  partition(cluster = cl)

cluster_eval(cl, {
  pryr::mem_used() # 671 MB
})
```

A work around, of course, is to partition on the nested df, but a potential improvement to the package is to prevent the identical elements of the list column from getting copied. I am (stuck) on Windows.

**Comment by hadley** [comment]
Could you please create a simple example? I don't quite understand what you're getting at here.

**Comment by kendonB** [comment]
I'm not really sure how to simplify the above, but I added some ``mem_used``'s that demonstrate the problem a bit better.

**Comment by kendonB** [comment]
On the main process, ``tmp`` is filled with pointers to ``iris``, whereas in ``tmp2``, the pointers get converted into copies. Is this more a problem with ``parallel``?

**Comment by Ax3man** [comment]
A clearer example (perhaps):

When creating a nested dataframe with duplicated data, the duplicated data is stored as pointers.

Example data:
```
tmp <- data_frame(i = rep(1:2, 2), d = list(iris, iris, iris, iris)) %>% 
  group_by(i)

# Source: local data frame [4 x 2]
# Groups: i [2]
# 
#       i                      d
#   <int>                 <list>
# 1     1 <data.frame [150 × 5]>
# 2     2 <data.frame [150 × 5]>
# 3     1 <data.frame [150 × 5]>
# 4     2 <data.frame [150 × 5]>
```
And the addresses of the repeated data:
```
purrr::map_chr(tmp$d, ~pryr::inspect(.)$address)
# [1] "0x3de3270" "0x3de3270" "0x3de3270" "0x3de3270"
```

On a partitioned data.frame this is not the case however:

```
cl <- create_cluster(2)
tmp2 <- tmp  %>% 
  partition(cluster = cl)

Call <- lazyeval::interp(~purrr::map_chr(xx$iris, ~pryr::inspect(.)$address), xx = as.name(tmp2$name))
cluster_call(cl, lazyeval::lazy_eval, Call)

# [[1]]
# [1] "0x12e02db8" "0x1204cb30"

# [[2]]
# [1] "0x12e02d10" "0x131bcad8"
```
While it makes complete sense that the addresses are not the same between nodes, Kendon expected that within nodes there is still no need for duplication. That is, the expectation here is to get two sets of two identical addresses.

**Comment by hadley** [comment]
Yeah because of the way R handles data serialisation, I doubt that there's anyway to preserve this property. In other words, this all happens at a level underneath multidplyr, so there's nothing I can do a about it.
