### ISSUE TITLE
rowwise fails on party_df

### ISSUE THREAD

**Issue by kendonB** [hadley/multidplyr#38]
`Error: is.data.frame(data) is not TRUE`

**Comment by mhlr** [comment]
+1 I could really use a fix for this. Thanks.

**Comment by cwbishop** [comment]
+1

**Comment by hadley** [comment]
`rowwise()` is not long for this world, so I'd recommend use something like http://r4ds.had.co.nz/many-models.html

**Comment by coletl** [comment]
Any chance this will change since `rowwise()` is no longer questioning? I'd love to be able to fit models rowwise and in parallel on nested data frames.
