### ISSUE TITLE
'Could not find function "gam"' in `group_by()` version of `models` in vignette

### ISSUE THREAD

**Issue by jwpestrak** [hadley/multidplyr#5]
I followed the vignette exactly (i.e., copy-and-paste) and ran into an issue towards the end:

**Works**

    system.time({
        models <- by_dest %>% 
            do(mod = gam(dep_delay ~ s(yday) + s(dep_time), data = .))
    })

**Doesn't Work**

    system.time({
        models <- common_dest %>% 
            group_by(dest) %>% 
            do(mod = gam(dep_delay ~ s(yday) + s(dep_time), data = .))
    })

Traceback:
Error in eval(expr, envir, enclos) : could not find function "gam" 
14 eval(expr, envir, enclos) 
13 eval(args[[j]]$expr, envir = env) 
12 do_.grouped_df(.data, .dots = lazyeval::lazy_dots(...)) 
11 do_(.data, .dots = lazyeval::lazy_dots(...)) 
10 do(., mod = gam(dep_delay ~ s(yday) + s(dep_time), data = .)) 
9 function_list[[k]](value) 
8 withVisible(function_list[[k]](value)) 
7 freduce(value, `_function_list`) 
6 `_fseq`(`_lhs`) 
5 eval(expr, envir, enclos) 
4 eval(quote(`_fseq`(`_lhs`)), env, env) 
3 withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
2 common_dest %>% group_by(dest) %>% do(mod = gam(dep_delay ~ s(yday) + 
    s(dep_time), data = .)) 
1 system.time({
    models <- common_dest %>% group_by(dest) %>% do(mod = gam(dep_delay ~ 
        s(yday) + s(dep_time), data = .))
})

**Comment by hadley** [comment]
Hmmm, is there a chance you had an old version of multidplyr installed? I changed the behaviour of `cluster_library()` fairly recently.
