### ISSUE TITLE
Unable to load packages into nodes

### ISSUE THREAD

**Issue by 12tafran** [hadley/multidplyr#50]
Hello,

I was trying to load a "dplyr" and "lubridate" into my nodes but I encounter the following error:

> cl <- create_cluster(cores=15)
Initialising 15 core cluster.
> set_default_cluster(cl)
> cluster_library(cl, "dplyr")
Error in checkForRemoteErrors(lapply(cl, recvResult)) : 
  15 nodes produced errors; first error: there is no package called 'dplyr'
> cluster_library(cl, "lubridate")
Error in checkForRemoteErrors(lapply(cl, recvResult)) : 
  15 nodes produced errors; first error: package or namespace load failed for 'lubridate' 

I have dplyr and lubridate loaded in my current R session so the package is there.  Is it problem with any of my packages?

Thanks in advance.

**Comment by xhudik** [comment]
in my case, your code is working fine:

```
library(multidplyr)
cl <- create_cluster(cores=15)
set_default_cluster(cl)
cluster_library(cl, "dplyr")
cluster_library(cl, "lubridate")

Attaching package: ‘lubridate’

The following object is masked from ‘package:base’:

    date

sessionInfo()

R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C 
```

**Comment by 12tafran** [comment]
Thanks for the help.

It was a recurring issues for a period of time but it resolved itself recently.  Thanks again.

**Comment by akshaykadidal** [comment]
I get his error now.
