### ISSUE TITLE
output to separate files on each cluster

### ISSUE THREAD

**Issue by ChiWPak** [hadley/multidplyr#53]
Not an issue but I'd like to output data in party_df objects to separate files on each cluster. With data.frames, I can do this:
library(readr)
data %>% write_tsv( ., file )
But write_tsv is not compatible with party_df. 
Anyone get this to work?

**Comment by Ax3man** [comment]
Use something like `mtcars %>% partition(cyl) %>% do(readr::write_tsv(., paste0(.$cyl[1], '.tsv')))`.

These kinds of questions may be better suited for stackoverflow.

**Comment by ChiWPak** [comment]
Thanks for the response. I'm closing this issue. (Sorry for posting here. Just didn't see a lot of posts on multidplyr on stackoverflow...)
