### ISSUE TITLE
arrange function does not work in multidplyr

### ISSUE THREAD

**Issue by kyp0717** [hadley/multidplyr#55]
## R CODE:
bel.rx.clm <- rbind(bel.rx.clms.2015d,bel.rx.clms.2016d) %>% 
              select(ENROLID, SVCDATE) %>% 
              arrange(SVCDATE)

cluster <- create_cluster(16)

bel.cohort.idx <- bel.rx.clm %>% 
                  partition(ENROLID,cluster=cluster) %>% 
                  arrange(SVCDATE) %>% first() %>% collect()

## ERROR

Error in UseMethod("arrange_") : 
  no applicable method for 'arrange_' applied to an object of class "party_df"

**Comment by Ax3man** [comment]
See #49.
