### ISSUE TITLE
multidplyr throws warning when used with dplyr 0.7.0

### ISSUE THREAD

**Issue by miho87** [hadley/multidplyr#57]
Using multidplyr with dplyr 0.7.0 generates the following warning:
`group_indices_.grouped_df ignores extra arguments`

Minimal example:
`mtcars %>% partition(cyl) %>% collect()`

It seems to have no impact on the calculated results, but I am not sure if that's always the case...

**Comment by MGousseff** [comment]
I encounter this problem as well. Thought it did no harm, but I do get problems in a more complex function...

**Comment by hadley** [comment]
This appears to be fixed by latest updates.
