### ISSUE TITLE
partition fails to complete

### ISSUE THREAD

**Issue by impactanalysts** [hadley/multidplyr#62]
I'm following the multidplyr example given in the introduction, and R got stuck on the first multidplyr command (partition); the command doesn't complete (I've let it run 15 minutes, which seems like more than enough time). 

    #> flights1 <- partition(flights, flight)
    Initializing 3 core cluster.

Looking at the system time from the example, it should have completed quickly:

    #>    user  system elapsed 
    #>   0.434   0.057   0.967

for me, the command has been running 15 minutes now. 

What should I try to fix this problem?

This is with R 3.4.3 on an iMac running High Sierra (10.13.3) with 32Gb memory.

<strong>UPDATE:</strong>
To reproduce the error on a different system, I ran the same commands on my Macbook Pro (also OSX 10.13.3, R 3.4.3).

    #> system.time(flights1 <- partition(flights, flight))
    Initialising 7 core cluster:
  
    #>    user  system elapsed 
    #>   0.796   0.091   1.188

So this appears to be a machine or system configuration specific issue. 

Still, I would appreciate any advice on things to try to get multidplyr working on my iMac.

**Comment by hadley** [comment]
No idea, sorry, but I'm about to replace the backend of multidplyr that should be more robust and will give me a great ability to diagnose problems.
