### ISSUE TITLE
‘multidyplr’ is not available (for R version 3.4.3)

### ISSUE THREAD

**Issue by njudd** [hadley/multidplyr#65]
Can't seem to install.packages("multidplyr") with R version 3.4.3, I'm assuming this also holds for 3.4.4 which was released on the 15th.

**Comment by Nihasa** [comment]
There haven't been many commits in the past year or so. It seems like this package is not being actively maintained.

**Comment by hadley** [comment]
multiplyr is not yet on CRAN.
