### ISSUE TITLE
Error in UseMethod("complete_"): no applicable method for 'complete_' applied to an object of class "party_df"

### ISSUE THREAD

**Issue by SGMStalin** [hadley/multidplyr#68]
Hi, I was trying to compare times between traditional `dplyr` package and `multidplyr` package. I found that the `complete` function is not available for `multidplyr` package. I think that I understand why it can't works in `multidplyr`, but I can't figure out how to solve it, is there some solution for that?

### Technical Information
Just in case...
I am running the code in 
`R version 3.5.1 (2018-07-02)`
`Platform: x86_64-pc-linux-gnu (64-bit)`
`Running under: Ubuntu 18.04.1 LTS`

### Code used
_(I could share the data if you need, but I think that the code is understable)_

`davis_pluvio1 <- partition(davis_pluvio, cluster = create_cluster(4))`
`cluster_library(davis_pluvio1, packages = "lubridate")`

`system.time(`
`davis_pluvio2 <- davis_pluvio1 %>%`
`  mutate_at(.vars = vars(matches("Hora")), `
`            funs(parse_date_time(., c("dmy HM", "mdy HM")))) %>%`
`  select(hora_inicio = Hora.Inicio,`
`         agregado = Agregado, calibrado = Calibrado) %>% `
**`  complete(hora_inicio = seq(min(hora_inicio, na.rm = T), `**
**`                            max(hora_inicio, na.rm = T), "5 mins")) %>% `**
`  mutate(calibrado = round(calibrado, digits = 4),`
`         hora_fin = hora_inicio + minutes(x = 5))`
`)`

_Any suggestion or question is welcome...
**Regards**_

**Comment by hadley** [comment]
multidplyr only supports dplyr verbs currently.
