### ISSUE TITLE
Error in checkForRemoteErrors(lapply(cl, recvResult)) :    7 nodes produced errors; first error: Evaluation error: object 'nearby_sensors' not found.

### ISSUE THREAD

**Issue by philiporlando** [hadley/multidplyr#69]
Is there an equivalent of  `snow::clusterExport()` in `multidplyr`? I'm unable to perform the following in parallel. Each node needs to have a `nearby_sensors` object.

`nearby_sensors <- c("A", "B", "C", "D")`
`df1 <- partition(df, id)`
`df2 <- df1 %>% dplyr::filter(id %in% nearby_sensors)`
`df3 <- collect(df2)`

`Error in checkForRemoteErrors(lapply(cl, recvResult)) : 7 nodes produced errors; first error: Evaluation error: object 'nearby_sensors' not found.`

**Comment by mstr3336** [comment]
I think I'm having a similar problem - multidplyr isn't finding variables from the calling (Or in my case, from the calling environment of `dplyr::do` and so is throwing errors.
It's a real shame because its halved my wall-time for my problem.

This is probably more of a problem with the implementation of tidyeval in multidplyr.
Maybe try using !! or some over tidy eval stuff to see if you can evaluate before executing? 
I will give an example.

**Comment by mstr3336** [comment]
Throws an error:
object 'maximum_merge_gap_hours' not found
```{r}
    df %<>%
      multidplyr::partition(PERSON_KEY) %>%
      multidplyr::cluster_library("journeyr") %>%
      dplyr::do(
        link_encs_in_groups(., max_gap_hours = maximum_merge_gap_hours)) %>%
      dplyr::collect()
```

**Comment by mstr3336** [comment]
Throws an error:
object 'maximum_merge_gap_hours' not found
```{r}
fun <- function(df, maximum_merge_gap_hours = 24){
  has_multi <- requireNamespace("multidplyr", quietly = TRUE)
  if (has_multi){
    df %<>%
      multidplyr::partition(group_var) %>%
      multidplyr::cluster_library("my_lib") %>%
      dplyr::do(
        link_encs_in_groups(., max_gap_hours = dplyr::enexpr(maximum_merge_gap_hours))) %>%
      dplyr::collect()
  }
```

**Comment by iago-pssjd** [comment]
I think the equivalent of `snow::clusterExport()` in `multidplyr` is `cluster_assign_value`. At least,it solved my problem (similar to yours), following the steps given by [this blog](http://blog.aicry.com/multidplyr-dplyr-meets-parallel-processing/index.html).
